language: java
jdk:
  - openjdk11

install: true

script:
  - ./mvnw clean install org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dmaven.javadoc.skip=true -Dsonar.projectKey=gazbert_spring-boot-rabbit-app -Dsonar.organization=gazbert-github

addons:
  sonarcloud:
    organization: "gazbert-github"
    token:
      secure: "KXy9o3/JxzqCKu8BBxbnmhSaTLdZqkrCcMrXQw5rhL0/3PTPinVD1YSVfB1WoaGVHmyCsRMvSNXBVqOjpHdYB6HBPqOe0CGHcgEltjI81NM/y1KtJgyAJ5JS828Rs8oKKYbUxA+o1g+ArSPtUBnuxEpMExm2ROZHVeAjUQkFzzBJTIKfKeyf3uRGyKDVzOk9ESFb3JkloVgq6abVDgKKvoMvQOTW6i8A8uwlQp81/D0M4zWroR39Z3UmtNgWCHITjkiZGqe47e9GlmxM9WyvwGxNV2lzs54Ps21xhwUAFduZuYmuRy6wTQgJjFpDkjYL5ffW/qh3xoNM/LR6xaOWIhOH4GqXv6hf3+oZwxF6mQpPBXtcfsJWiUKXfjRK1fTuRqojXiMolnes/Xjn8NaMPJVSL1NtFOtxHycISD5R9ez4K3CYKYTGIpjTv6BjFUahWMhStOCJ2WC5jGUF7Za+u4QKc6bjwAspHxo5Z9QFTBUZkGnc106BUpLdsMYWbh0dDeIQu9oPGq71Ukk2A+Z2ldIL1xwXzz2TYqfeJC3qmBOCMWt0CrFrdWQOAO4+x9fp1szOD0/hQQsatgWq8YuceaVDWZ6lILFVkfy30UvihYuFvR3KB8iTm01F08vPZwhN6DtV6ULAnzPBr+c0JOekQLiVuqBTkSDJcTZR19VvR6g="

